### ISSUE TITLE
How to use with angular 1

### ISSUE THREAD

**Issue by dbdario025** [lancetipton04/quill-video-resize#1]
Could you please put an example about the use of this with angular1, maybe the process can be more easy.

Thanks.

**Comment by lancetipton** [comment]
I'll try and do this, this weekend.

**Comment by lancetipton** [comment]
@dbdario025 Hey I know you asked a while ago, but I just added an example with react. I know you where asking for angular, but I never had an opportunity to do it. For the react example go [here](https://github.com/lancetipton/react-quill-experiment)

**Comment by dbdario025** [comment]
@lancetipton Thank you 👍 :)
